//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eking.News {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eking.News.LocalizedText_vi", typeof(LocalizedText_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du học.
        /// </summary>
        internal static string AbroadStudy {
            get {
                return ResourceManager.GetString("AbroadStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh doanh.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện ảnh.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe hơi.
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giáo dục.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải trí.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luật pháp.
        /// </summary>
        internal static string Law {
            get {
                return ResourceManager.GetString("Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chung.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm....
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe máy.
        /// </summary>
        internal static string Motobike {
            get {
                return ResourceManager.GetString("Motobike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thần bí.
        /// </summary>
        internal static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ trực tuyến.
        /// </summary>
        internal static string OnlineServices {
            get {
                return ResourceManager.GetString("OnlineServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        internal static string Recruitement {
            get {
                return ResourceManager.GetString("Recruitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin liên quan.
        /// </summary>
        internal static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã hội.
        /// </summary>
        internal static string SocialLife {
            get {
                return ResourceManager.GetString("SocialLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể thao.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ.
        /// </summary>
        internal static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thế giới.
        /// </summary>
        internal static string TheWorld {
            get {
                return ResourceManager.GetString("TheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương tiện đi lại.
        /// </summary>
        internal static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới trẻ.
        /// </summary>
        internal static string YoungPeople_Love {
            get {
                return ResourceManager.GetString("YoungPeople_Love", resourceCulture);
            }
        }
    }
}
