// Generated by CoffeeScript 1.4.0

ko.bindingHandlers.winJsUserRating = {
  init: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
    return element.winControl.onchange = function() {
      return valueAccessor()(element.winControl.userRating);
    };
  },
  update: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
    return element.winControl.userRating = ko.utils.unwrapObservable(valueAccessor());
  }
};
