//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eking.News.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eking.News.Tests.RES", typeof(RES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; itemscope=&quot;itemscope&quot; itemtype=&quot;http://schema.org/WebPage&quot;&gt;
        ///&lt;head id=&quot;ctl00_Head1&quot;&gt;&lt;title&gt;
        /// “Trảm” hàng loạt taxi kém chất lượng tại bến xe Gia Lâm - Xã hội - Dân trí
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;&lt;meta content=&quot;INDEX,FOLLOW&quot; name=&quot;robots&quot; /&gt;&lt;meta id=&quot;ctl00_metaImage&quot; itemprop=&quot;image&quot; /&gt;&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dantri_entry_text {
            get {
                return ResourceManager.GetString("dantri_entry_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; itemscope=&quot;itemscope&quot; itemtype=&quot;http://schema.org/WebPage&quot;&gt;
        ///&lt;head id=&quot;ctl00_Head1&quot;&gt;&lt;title&gt;
        /// X&amp;#227; hội - Dân trí
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;&lt;meta content=&quot;INDEX,FOLLOW&quot; name=&quot;robots&quot; /&gt;&lt;meta id=&quot;ctl00_metaImage&quot; itemprop=&quot;image&quot; /&gt;&lt;meta id=&quot;ctl00_metaRefresh&quot; http-equiv=&quot;REFRESH&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dantri_master_text {
            get {
                return ResourceManager.GetString("dantri_master_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html id=&quot;XenForo&quot; lang=&quot;&quot; dir=&quot;LTR&quot; class=&quot;Public LoggedOut Sidebar&quot; xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot;&gt;
        ///&lt;head&gt;
        ///
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	
        ///		&lt;base href=&quot;http://www.tinhte.vn/&quot; /&gt;
        ///		&lt;script&gt;
        ///			var _b = document.getElementsByTagName(&apos;base&apos;)[0], _bH = &quot;http://www.tinhte.vn/&quot;;
        ///			if (_b &amp;&amp; _b.href != _bH) _b.href = _bH;
        ///		&lt;/script&gt;
        ///	
        ///
        ///	&lt;title&gt;Hình ảnh mở hộp điện thoại iPhone 5 | Tinhte.vn - Cộng đồng Khoa học &amp;amp; Công nghệ&lt;/title&gt;
        ///	
        ///	&lt;noscript&gt;&lt;style&gt;.JsOnly { dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tinhte_entry_text {
            get {
                return ResourceManager.GetString("tinhte_entry_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html id=&quot;XenForo&quot; lang=&quot;&quot; dir=&quot;LTR&quot; class=&quot;Public LoggedOut Sidebar&quot; xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot;&gt;
        ///&lt;head&gt;
        ///
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	
        ///		&lt;base href=&quot;http://www.tinhte.vn/&quot; /&gt;
        ///		&lt;script&gt;
        ///			var _b = document.getElementsByTagName(&apos;base&apos;)[0], _bH = &quot;http://www.tinhte.vn/&quot;;
        ///			if (_b &amp;&amp; _b.href != _bH) _b.href = _bH;
        ///		&lt;/script&gt;
        ///	
        ///
        ///	&lt;title&gt;Tinhte.vn - Cộng đồng Khoa học &amp;amp; Công nghệ&lt;/title&gt;
        ///	
        ///	&lt;noscript&gt;&lt;style&gt;.JsOnly { display: none !important; }&lt;/style&gt;&lt;/nosc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tinhte_master_text {
            get {
                return ResourceManager.GetString("tinhte_master_text", resourceCulture);
            }
        }
    }
}
