//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eking.News.AdminSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawEntryModel
    {
        public RawEntryModel()
        {
            this.Children = new HashSet<RawEntryModel>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<RawEntryModel> Children { get; set; }
        public virtual RawEntryModel Parent { get; set; }
    }
}
