// Generated by CoffeeScript 1.4.0
var HomeViewModel,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

HomeViewModel = (function() {

  function HomeViewModel() {
    this.generateSampe = __bind(this.generateSampe, this);

    var list,
      _this = this;
    list = new WinJS.Binding.List();
    this.ItemsSource = list.createGrouped(function(item) {
      return item.GroupId;
    }, function(item) {
      return item.Items;
    });
  }

  HomeViewModel.prototype.generateSampe = function() {
    return [
      {
        "GroupName": "Group1",
        "GroupId": "01",
        "Items": [
          {
            "Id": "01",
            "Title": "PBB",
            "Vote": "4"
          }, {
            "Id": "02",
            "Title": "PB2",
            "Vote": "5"
          }
        ]
      }, {
        "GroupName": "Group2",
        "GroupId": "02",
        "Items": [
          {
            "Id": "01",
            "Title": "TV",
            "Vote": "0"
          }, {
            "Id": "02",
            "Title": "TV02",
            "Vote": "5"
          }
        ]
      }
    ];
  };

  return HomeViewModel;

})();
